apiVersion: 1

datasources:
  - uid: loki
    orgId: 1
    name: Loki
    type: loki
    typeName: Loki
    access: proxy
    url: http://localhost:3100
    password: ''
    user: ''
    database: ''
    basicAuth: false
    isDefault: false
    readOnly: false
    editable: true
