name: Build and test latest code changes
on: 
  push:
    branches:
      - 'main'

jobs:
  everything:
    name: Build and test latest code changes
    runs-on: ubuntu-latest
    steps:
      - name: Setup cache
        uses: actions/cache@v2
        with:
          key: querido-diario-cache
          path: |
            ~/.local/share/containers

      - name: Checkout source code
        uses: actions/checkout@master

      - name: Build container image
        run: |
          make build

      - name: Run tests
        run: |
          make test
