name: Security scan

on:
  pull_request:
    branches: [ main ]
  schedule:
    - cron: '0 6 * * *'
  workflow_dispatch:

permissions:
  contents: read

jobs:
  trivy-repo:
    name: Scan repository (SAST/Deps)
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Run Trivy filesystem scan
        uses: aquasecurity/trivy-action@0.28.0
        with:
          scan-type: 'fs'
          ignore-unfixed: true
          format: 'sarif'
          output: 'trivy-repo.sarif'
          severity: 'CRITICAL,HIGH'
      - name: Upload SARIF
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: trivy-repo.sarif

  trivy-image:
    name: Scan image built from Dockerfile
    runs-on: ubuntu-latest
    needs: trivy-repo
    steps:
      - uses: actions/checkout@v4
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Build local image
        run: |
          docker build -f Dockerfile -t local/qd-api:scan .
      - name: Scan Docker image
        uses: aquasecurity/trivy-action@0.28.0
        with:
          image-ref: 'local/qd-api:scan'
          format: 'table'
          ignore-unfixed: true
          severity: 'CRITICAL,HIGH'